name: Build
on:
  push:
    branches:
      - master

jobs:
  build-uiw-admin:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Look Changelog
      uses: jaywcjlove/changelog-generator@v1.3.9
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - run: yarn install
    - run: yarn run build

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        package-path: ./packages/uiw-admin/package.json

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.3.9
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/uiw@${{steps.changelog.outputs.version}}/file/README.md)
          
          ${{ steps.changelog.outputs.compareurl }}

          ${{ steps.changelog.outputs.changelog }}

    - run: yarn run build:website
      env:
        CI: false

    - run: npm run www:build
    
    - name: Compress uiw-admin Example.
      run: zip -r -y uiw-admin.zip . -x "node_modules/*" -x "build/*" -x "dist/*" -x "coverage/*" -x ".eslintcache" -x "sandbox.config.json" -x ".stackblitzrc"
      working-directory: examples/base
    - run: cp -rp ./examples/base/uiw-admin.zip ./examples/website/build

    - name: Heroku -> Setting the stack
      working-directory: examples/base
      run: |
        cat > ~/app.json <<EOF
        {
          "stack": "heroku-20"
        }
        EOF

    - name: Deploy to heroku.com
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: heroku
        publish_dir: ./examples/base

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./examples/website/build

    - run: npm install @jsdevtools/npm-publish -g
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/Exceptions/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/authorized/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/basic-layouts/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/components/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/config/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/document-title/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/layout-tabs/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/models/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/plugins/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/router-control/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/uiw-admin/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/user-login/package.json
    - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/utils/package.json
